### ISSUE TITLE
Error creating a d.ts from fb javascript api

### ISSUE THREAD

**Issue by EduardoJaco** [BCJTI/d-ts-gen#2]
Then d-ts-gen added a class inside the module: 

``` typescript
declare module "fb" {
  class fb {
  ...
  }
```

I removed it and exported all the methods then it worked.

``` typescript
declare module "fb" {
        export function api(obj? : any,obj2? : any,obj3? : any) : any;
        export function napi(obj? : any) : any;
        export function getAccessToken(obj? : any) : any;
        export function setAccessToken(accessToken : any) : any;
        export function parseSignedRequest( obj? : any) : any;
        export function getLoginUrl(opt : any) : any;
        export function options(keyOrOptions : any) : any;
        export var version: string;
        export function FacebookApiException(res : any) : any;
}
```

[EDIT]: changed the format of code.

**Comment by Bigous** [comment]
The export is not necessary in d.ts files.

The sequence of optional objects as parameter will need some implementation... reverse engeneering... and will not be implemented soon...

The optional parameters with only one parameter is implemented at version 0.2.0. But after the optional parameter, the generator cannot know if it should have more parameters...
